// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7yTFQQOPL_t7YdQhUWZgR_-c8A-WO9Kg',
    appId: '1:491467723154:web:37d9528657c6fb3b50314b',
    messagingSenderId: '491467723154',
    projectId: 'soyamoroso-8613c',
    authDomain: 'soyamoroso-8613c.firebaseapp.com',
    storageBucket: 'soyamoroso-8613c.firebasestorage.app',
    measurementId: 'G-K3JL3S8T68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxXbUeNU8kA_BKPfYm7_YaK58aN30J3B4',
    appId: '1:491467723154:android:f3e0f4e413e5f21650314b',
    messagingSenderId: '491467723154',
    projectId: 'soyamoroso-8613c',
    storageBucket: 'soyamoroso-8613c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-d9Ega8cxf5IumFWb-Osv0QrEBDuRuXw',
    appId: '1:491467723154:ios:f247b62de0cb82dd50314b',
    messagingSenderId: '491467723154',
    projectId: 'soyamoroso-8613c',
    storageBucket: 'soyamoroso-8613c.firebasestorage.app',
    iosBundleId: 'com.example.testandoTokenvaliaut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-d9Ega8cxf5IumFWb-Osv0QrEBDuRuXw',
    appId: '1:491467723154:ios:f247b62de0cb82dd50314b',
    messagingSenderId: '491467723154',
    projectId: 'soyamoroso-8613c',
    storageBucket: 'soyamoroso-8613c.firebasestorage.app',
    iosBundleId: 'com.example.testandoTokenvaliaut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7yTFQQOPL_t7YdQhUWZgR_-c8A-WO9Kg',
    appId: '1:491467723154:web:2c15808d9d59d14550314b',
    messagingSenderId: '491467723154',
    projectId: 'soyamoroso-8613c',
    authDomain: 'soyamoroso-8613c.firebaseapp.com',
    storageBucket: 'soyamoroso-8613c.firebasestorage.app',
    measurementId: 'G-33FBZPJPBZ',
  );
}
